### ISSUE TITLE
# EPIC - Finish writing documentation

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#22]
Reopening with tasks to complete:
- [x] Finish writing the Contributing Guidelines file
- [x] Add additional details to README file.
- [x] Record a Show Case Video
- [x] Move Example image into folder inside of documentation.
- [x] Proof read all documentation.
- [x] Ensure that below EPICs are complete
- [x] #59 
- [x] #66 
- [x] #68 
- [x] #138
- Also renamed branch from `22/document/insights` to `22/epic/documentation`
  You can update your repository with 
  ``` 
  git branch -m 22/documentation/insights 22/epic/documentation
  git fetch origin
  git branch -u origin/22/epic/documentation 22/epic/documentation
  git remote set-head origin -a
  ```
  If you want to help work on this issue more but it will not be a requirement from anybody to help with the documentation.

**Comment by mnichols08** [comment]
https://github.com/chingu-voyages/v47-tier1-team-04/pulse

**Comment by mnichols08** [comment]
Somehow the branch that this issue solved was deleted =(


Please be careful not to do this when making pull requests and merging them.

**Comment by mnichols08** [comment]
I am going to leave the branch that is attached to this issue open for a while so I don't have to create a new branch later as I modify documentation. But this issue can be marked closed now.

**Comment by mnichols08** [comment]
Reopening with tasks to complete:
- [x] Finish writing the Contributing Guidelines file
- [x] Add additional details to README file.
- [x] Record a Show Case Video
- [x] Move Example image into folder inside of documentation.
- [x] Proof read all documentation.
- Also renamed branch from `22/document/insights` to `22/epic/documentation`
  You can update your repository with 
  ``` 
  git branch -m 22/documentation/insights 22/epic/documentation
  git fetch origin
  git branch -u origin/22/epic/documentation 22/epic/documentation
  git remote set-head origin -a
  ```
  If you want to help work on this issue more but it will not be a requirement from anybody to help with the documentation.
