### ISSUE TITLE
Create a boilerplate for the HTML

### ISSUE THREAD

**Issue by mnichols08** [chingu-voyages/v47-tier1-team-04#87]
# Tasks
- [x] Declare the document as HTML5 by writing `<!DOCTYPE html>` on the top line.
- [x] Create an `<html>` element with an attribute `lang`. An attribute is defined as any other word other than the first inside of an HTML `<element>`. A value for an attribute is declared by an `=` such as below with the example for importing a `stylesheet` into the document. The value should be set to `en` for English.
- [x] Create a `<head>` element inside of the `<html>` element.
  - [x] Inside of the `<head>` element add two `<meta>` elements.
     - [x] In the first give it an attribute of `charset` and value of `UTF-8` to define the universal character set.
     - [x] For the second, give it two attributes. The first should be `name` and the second `content`. The `name` should be set to `viewport` and the `content` should be set to `width=device-width, initial-scale=1.0`. This defines the base viewport for different screens.
  - [x] Set the page title by adding a `<title>` element with appropriate text to define title.
  - [x] Place a `<link>` in `<head>` to load the CSS stylesheet. 
- [x] Place script appropriately somehow in the document (there is more than one place you can put this.)
- [x] Create a `<body>` element underneath of the `<head>` element but still inside of the `<html>`.
